"""PRISM-Q: performance-first quantum circuit simulator.

Thin Python bindings over the Rust ``prism-q`` crate. The compiled extension
``prism_q._prism_q`` provides the implementation; this package re-exports it.
"""

import sys as _sys

from ._prism_q import (
    __version__,
    BackendKind,
    BondReport,
    BraketProgram,
    Circuit,
    CircuitBuilder,
    ClassicalCondition,
    CompiledSampler,
    CountsResult,
    Decoder,
    DeviceCalibration,
    DetectorErrorModel,
    DistributedContext,
    EntropyResult,
    ExpectationResult,
    Gate,
    GateFilter,
    GpuContext,
    GpuInfo,
    NoiseBuilder,
    NoiseChannel,
    NoiseModel,
    ObservableExpectation,
    ObservableVariance,
    OverlapResult,
    Parameters,
    PauliObservable,
    PreparedCircuit,
    PrismError,
    QecBasis,
    QecNoise,
    QecProgram,
    QecResult,
    RecordRef,
    ReducedDensityMatrix,
    RunMetadata,
    RunOutcome,
    SaveSpec,
    ShotsResult,
    Simulation,
    StabilizerBackend,
    circuits,
    gpu_info,
    parse_braket,
    parse_qasm,
    parse_qasm_parametric,
    run_batch,
    run_qasm,
    simulate,
)

_sys.modules[__name__ + ".circuits"] = circuits

__all__ = [
    "__version__",
    "BackendKind",
    "BondReport",
    "BraketProgram",
    "Circuit",
    "CircuitBuilder",
    "ClassicalCondition",
    "CompiledSampler",
    "CountsResult",
    "Decoder",
    "DeviceCalibration",
    "DetectorErrorModel",
    "DistributedContext",
    "EntropyResult",
    "ExpectationResult",
    "Gate",
    "GateFilter",
    "GpuContext",
    "GpuInfo",
    "NoiseBuilder",
    "NoiseChannel",
    "NoiseModel",
    "ObservableExpectation",
    "ObservableVariance",
    "OverlapResult",
    "Parameters",
    "PauliObservable",
    "PreparedCircuit",
    "PrismError",
    "QecBasis",
    "QecNoise",
    "QecProgram",
    "QecResult",
    "RecordRef",
    "ReducedDensityMatrix",
    "RunMetadata",
    "RunOutcome",
    "SaveSpec",
    "ShotsResult",
    "Simulation",
    "StabilizerBackend",
    "circuits",
    "gpu_info",
    "parse_braket",
    "parse_qasm",
    "parse_qasm_parametric",
    "run_batch",
    "run_qasm",
    "simulate",
]
