"""PRISM-Q: performance-first quantum circuit simulator.

Thin Python bindings over the Rust ``prism-q`` crate. The compiled extension
``prism_q._prism_q`` provides the implementation; this package re-exports it.
"""

import sys as _sys
import warnings as _warnings

from ._prism_q import (
    __version__,
    BackendKind,
    BondReport,
    BpOsdDecoder,
    BraketProgram,
    Circuit,
    CircuitBuilder,
    ClassicalCondition,
    CompiledSampler,
    CountsResult,
    DeviceCalibration,
    DetectorErrorModel,
    DistributedContext,
    DriftDistribution,
    DynamicProgram,
    DynamicProgramBuilder,
    EntropyResult,
    ErrorChainComplex,
    ExpectationResult,
    MarginalsResult,
    Gate,
    GateFilter,
    GateTimes,
    GpuContext,
    GpuInfo,
    MatchingDecoder,
    NoiseBuilder,
    NoiseChannel,
    NoiseModel,
    ObservableExpectation,
    ObservableVariance,
    OverlapResult,
    Parameters,
    PauliObservable,
    PreparedCircuit,
    PrismError,
    ProgramSimulation,
    QecBasis,
    QecCircuitNoise,
    QecNoise,
    QecObservableEstimate,
    QecProgram,
    QecRecordRef,
    QecSampleResult,
    ReducedDensityMatrix,
    RunMetadata,
    RunOutcome,
    SaveSpec,
    ShotsResult,
    Simulation,
    StabilizerBackend,
    ThreadPool,
    UnionFindDecoder,
    circuits,
    gpu_info,
    noisy_marginals_analytical,
    parse_braket,
    parse_qasm,
    parse_qasm_dynamic,
    parse_qasm_parametric,
    run_batch,
    run_qasm,
    simulate,
    simulate_program,
)

_sys.modules[__name__ + ".circuits"] = circuits

__all__ = [
    "__version__",
    "BackendKind",
    "BondReport",
    "BpOsdDecoder",
    "BraketProgram",
    "Circuit",
    "CircuitBuilder",
    "ClassicalCondition",
    "CompiledSampler",
    "CountsResult",
    "DeviceCalibration",
    "DetectorErrorModel",
    "DistributedContext",
    "DriftDistribution",
    "DynamicProgram",
    "DynamicProgramBuilder",
    "EntropyResult",
    "ErrorChainComplex",
    "ExpectationResult",
    "MarginalsResult",
    "Gate",
    "GateFilter",
    "GateTimes",
    "GpuContext",
    "GpuInfo",
    "MatchingDecoder",
    "NoiseBuilder",
    "NoiseChannel",
    "NoiseModel",
    "ObservableExpectation",
    "ObservableVariance",
    "OverlapResult",
    "Parameters",
    "PauliObservable",
    "PreparedCircuit",
    "PrismError",
    "ProgramSimulation",
    "QecBasis",
    "QecCircuitNoise",
    "QecNoise",
    "QecObservableEstimate",
    "QecProgram",
    "QecRecordRef",
    "QecSampleResult",
    "ReducedDensityMatrix",
    "RunMetadata",
    "RunOutcome",
    "SaveSpec",
    "ShotsResult",
    "Simulation",
    "StabilizerBackend",
    "ThreadPool",
    "UnionFindDecoder",
    "circuits",
    "gpu_info",
    "noisy_marginals_analytical",
    "parse_braket",
    "parse_qasm",
    "parse_qasm_dynamic",
    "parse_qasm_parametric",
    "run_batch",
    "run_qasm",
    "simulate",
    "simulate_program",
]

_DEPRECATED_NAMES = {
    "Decoder": "UnionFindDecoder",
    "QecResult": "QecSampleResult",
    "RecordRef": "QecRecordRef",
}


def __getattr__(name):
    replacement = _DEPRECATED_NAMES.get(name)
    if replacement is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    _warnings.warn(
        f"prism_q.{name} is deprecated and will be removed in the next minor release; "
        f"use prism_q.{replacement}",
        DeprecationWarning,
        stacklevel=2,
    )
    return globals()[replacement]
