"""Type stubs for the compiled ``prism_q._prism_q`` extension module."""

from enum import Enum
from typing import Optional

import numpy as np
import numpy.typing as npt

__version__: str

class PrismError(Exception):
    """Error raised by PRISM-Q operations."""

class Gate:
    @staticmethod
    def id() -> "Gate": ...
    @staticmethod
    def x() -> "Gate": ...
    @staticmethod
    def y() -> "Gate": ...
    @staticmethod
    def z() -> "Gate": ...
    @staticmethod
    def h() -> "Gate": ...
    @staticmethod
    def s() -> "Gate": ...
    @staticmethod
    def sdg() -> "Gate": ...
    @staticmethod
    def t() -> "Gate": ...
    @staticmethod
    def tdg() -> "Gate": ...
    @staticmethod
    def sx() -> "Gate": ...
    @staticmethod
    def sxdg() -> "Gate": ...
    @staticmethod
    def cx() -> "Gate": ...
    @staticmethod
    def cz() -> "Gate": ...
    @staticmethod
    def swap() -> "Gate": ...
    @staticmethod
    def rx(theta: float) -> "Gate": ...
    @staticmethod
    def ry(theta: float) -> "Gate": ...
    @staticmethod
    def rz(theta: float) -> "Gate": ...
    @staticmethod
    def p(theta: float) -> "Gate": ...
    @staticmethod
    def rzz(theta: float) -> "Gate": ...
    @staticmethod
    def cphase(theta: float) -> "Gate": ...
    @staticmethod
    def cu(matrix: object) -> "Gate": ...
    @staticmethod
    def mcu(matrix: object, num_controls: int) -> "Gate": ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def name(self) -> str: ...

class Circuit:
    def __init__(self, num_qubits: int, num_classical_bits: int = 0) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_classical_bits(self) -> int: ...
    def gate_count(self) -> int: ...
    def t_count(self) -> int: ...
    def is_clifford_only(self) -> bool: ...
    def add_gate(self, gate: Gate, targets: list[int]) -> None: ...
    def add_measure(self, qubit: int, classical_bit: int) -> None: ...
    def add_reset(self, qubit: int) -> None: ...
    def add_barrier(self, qubits: list[int]) -> None: ...

class CircuitBuilder:
    def __init__(self, num_qubits: int, num_classical_bits: int = 0) -> None: ...
    def id(self, q: int) -> "CircuitBuilder": ...
    def x(self, q: int) -> "CircuitBuilder": ...
    def y(self, q: int) -> "CircuitBuilder": ...
    def z(self, q: int) -> "CircuitBuilder": ...
    def h(self, q: int) -> "CircuitBuilder": ...
    def s(self, q: int) -> "CircuitBuilder": ...
    def sdg(self, q: int) -> "CircuitBuilder": ...
    def t(self, q: int) -> "CircuitBuilder": ...
    def tdg(self, q: int) -> "CircuitBuilder": ...
    def sx(self, q: int) -> "CircuitBuilder": ...
    def sxdg(self, q: int) -> "CircuitBuilder": ...
    def rx(self, theta: float, q: int) -> "CircuitBuilder": ...
    def ry(self, theta: float, q: int) -> "CircuitBuilder": ...
    def rz(self, theta: float, q: int) -> "CircuitBuilder": ...
    def p(self, theta: float, q: int) -> "CircuitBuilder": ...
    def rzz(self, theta: float, q0: int, q1: int) -> "CircuitBuilder": ...
    def cx(self, control: int, target: int) -> "CircuitBuilder": ...
    def cz(self, q0: int, q1: int) -> "CircuitBuilder": ...
    def swap(self, q0: int, q1: int) -> "CircuitBuilder": ...
    def cphase(self, theta: float, control: int, target: int) -> "CircuitBuilder": ...
    def cu(self, matrix: object, control: int, target: int) -> "CircuitBuilder": ...
    def mcu(self, matrix: object, controls: list[int], target: int) -> "CircuitBuilder": ...
    def measure(self, qubit: int, classical_bit: int) -> "CircuitBuilder": ...
    def measure_all(self) -> "CircuitBuilder": ...
    def barrier(self, qubits: list[int]) -> "CircuitBuilder": ...
    def gate(self, gate: Gate, targets: list[int]) -> "CircuitBuilder": ...
    def build(self) -> Circuit: ...

class BackendKind:
    @staticmethod
    def auto() -> "BackendKind": ...
    @staticmethod
    def statevector() -> "BackendKind": ...
    @staticmethod
    def stabilizer() -> "BackendKind": ...
    @staticmethod
    def sparse() -> "BackendKind": ...
    @staticmethod
    def product_state() -> "BackendKind": ...
    @staticmethod
    def tensor_network() -> "BackendKind": ...
    @staticmethod
    def factored() -> "BackendKind": ...
    @staticmethod
    def factored_stabilizer() -> "BackendKind": ...
    @staticmethod
    def stabilizer_rank() -> "BackendKind": ...
    @staticmethod
    def mps(max_bond_dim: int = 256) -> "BackendKind": ...
    @staticmethod
    def stochastic_pauli(num_samples: int = 1000) -> "BackendKind": ...
    @staticmethod
    def deterministic_pauli(epsilon: float = 0.0, max_terms: int = 65536) -> "BackendKind": ...

class NoiseChannel:
    @staticmethod
    def pauli(px: float, py: float, pz: float) -> "NoiseChannel": ...
    @staticmethod
    def depolarizing(p: float) -> "NoiseChannel": ...
    @staticmethod
    def amplitude_damping(gamma: float) -> "NoiseChannel": ...
    @staticmethod
    def phase_damping(gamma: float) -> "NoiseChannel": ...
    @staticmethod
    def thermal_relaxation(t1: float, t2: float, gate_time: float) -> "NoiseChannel": ...
    @staticmethod
    def two_qubit_depolarizing(p: float) -> "NoiseChannel": ...
    @staticmethod
    def custom(kraus: list[object]) -> "NoiseChannel": ...

class NoiseModel:
    @staticmethod
    def uniform_depolarizing(circuit: Circuit, p: float) -> "NoiseModel": ...
    @staticmethod
    def with_amplitude_damping(circuit: Circuit, gamma: float) -> "NoiseModel": ...
    @staticmethod
    def empty(circuit: Circuit) -> "NoiseModel": ...
    def add_event(
        self, instruction_index: int, channel: NoiseChannel, qubits: list[int]
    ) -> None: ...
    def with_readout_error(self, p01: float, p10: float) -> None: ...
    def validate(self) -> None: ...
    def is_pauli_only(self) -> bool: ...

class RunOutcome:
    @property
    def classical_bits(self) -> list[bool]: ...
    @property
    def probabilities(self) -> Optional[npt.NDArray[np.float64]]: ...

class ShotsResult:
    @property
    def shots(self) -> list[list[bool]]: ...
    @property
    def num_shots(self) -> int: ...
    @property
    def num_classical_bits(self) -> int: ...
    def counts(self) -> dict[str, int]: ...

class CountsResult:
    @property
    def num_classical_bits(self) -> int: ...
    def counts(self) -> dict[str, int]: ...

class Simulation:
    def seed(self, seed: int) -> "Simulation": ...
    def backend(self, kind: BackendKind) -> "Simulation": ...
    def noise(self, model: NoiseModel) -> "Simulation": ...
    def run(self) -> RunOutcome: ...
    def shots(self, num_shots: int) -> ShotsResult: ...
    def sample_counts(self, num_shots: int) -> CountsResult: ...
    def marginals(self) -> list[tuple[float, float]]: ...
    def state_vector(self) -> npt.NDArray[np.complex128]: ...

class QecBasis(Enum):
    X = ...
    Y = ...
    Z = ...

class RecordRef:
    @staticmethod
    def absolute(index: int) -> "RecordRef": ...
    @staticmethod
    def lookback(distance: int) -> "RecordRef": ...

class QecNoise:
    @staticmethod
    def x_error(p: float) -> "QecNoise": ...
    @staticmethod
    def z_error(p: float) -> "QecNoise": ...
    @staticmethod
    def depolarize1(p: float) -> "QecNoise": ...
    @staticmethod
    def depolarize2(p: float) -> "QecNoise": ...

class QecProgram:
    def __init__(self, num_qubits: int) -> None: ...
    @staticmethod
    def from_text(text: str) -> "QecProgram": ...
    def set_options(
        self,
        shots: int,
        seed: int = 42,
        chunk_size: Optional[int] = None,
        keep_measurements: bool = True,
    ) -> None: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def num_measurements(self) -> int: ...
    @property
    def num_detectors(self) -> int: ...
    @property
    def num_observables(self) -> int: ...
    def push_gate(self, gate: Gate, targets: list[int]) -> None: ...
    def reset(self, basis: QecBasis, qubit: int) -> None: ...
    def measure(self, basis: QecBasis, qubit: int) -> int: ...
    def measure_z(self, qubit: int) -> int: ...
    def measure_x(self, qubit: int) -> int: ...
    def measure_pauli_product(self, terms: list[tuple[QecBasis, int]]) -> int: ...
    def detector(
        self, records: list[RecordRef], coords: Optional[list[float]] = None
    ) -> int: ...
    def detector_lookback(self, distances: list[int]) -> int: ...
    def observable_include(self, observable: int, records: list[RecordRef]) -> None: ...
    def postselect(self, records: list[RecordRef], expected: bool) -> None: ...
    def noise(self, channel: QecNoise, targets: list[int]) -> None: ...
    def run(self) -> "QecResult": ...

class QecResult:
    @property
    def total_shots(self) -> int: ...
    @property
    def accepted_shots(self) -> int: ...
    @property
    def discarded_shots(self) -> int: ...
    @property
    def logical_errors(self) -> list[int]: ...
    def logical_error_rates(self) -> list[float]: ...
    def survivor_rate(self) -> float: ...
    @property
    def detectors(self) -> npt.NDArray[np.bool_]: ...
    @property
    def observables(self) -> npt.NDArray[np.bool_]: ...
    @property
    def measurements(self) -> npt.NDArray[np.bool_]: ...

def parse_qasm(source: str) -> Circuit: ...
def run_qasm(source: str, seed: int) -> RunOutcome: ...
def simulate(circuit: Circuit) -> Simulation: ...

class circuits:
    @staticmethod
    def qft(n: int) -> Circuit: ...
    @staticmethod
    def ghz(n: int) -> Circuit: ...
    @staticmethod
    def w_state(n: int) -> Circuit: ...
    @staticmethod
    def random(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def hardware_efficient_ansatz(n: int, layers: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def clifford_heavy(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def clifford_random_pairs(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def qaoa(n: int, layers: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def single_qubit_rotation(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def clifford_t(n: int, depth: int, t_fraction: float = 0.1, seed: int = 42) -> Circuit: ...
    @staticmethod
    def quantum_volume(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def cz_chain(n: int, depth: int, seed: int = 42) -> Circuit: ...
    @staticmethod
    def phase_estimation(n: int) -> Circuit: ...
    @staticmethod
    def independent_bell_pairs(n_pairs: int) -> Circuit: ...
    @staticmethod
    def independent_random_blocks(
        num_blocks: int, block_size: int, depth: int, seed: int = 42
    ) -> Circuit: ...
    @staticmethod
    def local_clifford_blocks(
        num_blocks: int, block_size: int, depth: int, seed: int = 42
    ) -> Circuit: ...
