"""Entry point for the cross-simulator comparison.

    python comparison/run_comparison.py --out comparison/results/run.json
    python comparison/run_comparison.py --check comparison/results/reference-<host>.json

`--check` re-runs the comparison and exits non-zero when a claim no longer
holds: a circuit hash that does not match the reference, a simulator whose
output diverges, or a verdict that flips. Absolute times are not checked,
because they do not carry across hardware. Ratios and verdicts do.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from typing import Any

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from harness import SCHEMA_VERSION, adapters, corpus, provenance, report  # noqa: E402

REPO_ROOT = provenance.REPO_ROOT
REFERENCE_SIMULATOR = "aer-statevector"
CARGO_FEATURES = "parallel"

DOCS_PREAMBLE = """# Comparative Measurements

<!-- Generated by `python comparison/run_comparison.py --docs`. Do not edit by hand. -->

"""

DOCS_FOOTER = """
## Reproducing

The harness, its adapters, and the build steps for each comparator are in
`comparison/README.md` in the repository. The run that produced this page is
committed as `comparison/results/reference-<host>.json`; `--check` against it
re-runs the comparison and exits non-zero when a circuit hash, an output, or a
verdict no longer matches.

```bash
python comparison/run_comparison.py --iterations 5 --qubits 16,20,24 \\
  --out comparison/results/run.json --markdown comparison/results/run.md
```

The [Benchmark Methodology](./guides/benchmarking.md) page states the controls
these numbers were taken under and what a comparison needs before it can be
cited.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--families", default="all", help="comma separated, or 'all'")
    parser.add_argument("--qubits", default="16,20,24", help="comma separated sizes")
    parser.add_argument(
        "--simulators",
        default=",".join(adapters.DEFAULT_SIMULATORS),
        help="comma separated adapter names; prismq is always included",
    )
    parser.add_argument("--iterations", type=int, default=5)
    parser.add_argument("--threads", type=int, default=os.cpu_count() or 1)
    parser.add_argument("--timeout-s", type=float, default=900.0, help="per call, per simulator")
    parser.add_argument("--tie-band-pct", type=float, default=10.0)
    parser.add_argument(
        "--equivalence-tvd",
        type=float,
        default=1e-5,
        help="a wrong circuit lands near 1e-1; qsim keeps float32 amplitudes, which land near 1e-6",
    )
    parser.add_argument("--headline-min-qubits", type=int, default=16)
    parser.add_argument("--out", default=None, help="write results JSON here")
    parser.add_argument("--markdown", default=None, help="write the rendered report here")
    parser.add_argument("--docs", default=None, help="write the documentation page here")
    parser.add_argument("--check", default=None, help="compare against a reference JSON")
    parser.add_argument("--no-build", action="store_true", help="skip building compare_runner")
    return parser.parse_args()


def build_runner() -> None:
    print("building compare_runner ...", flush=True)
    proc = subprocess.run(
        ["cargo", "build", "--release", "--features", CARGO_FEATURES, "--example", "compare_runner"],
        cwd=REPO_ROOT,
        check=False,
    )
    if proc.returncode != 0:
        sys.exit("cargo build failed")


def stats(samples: list[float]) -> dict[str, Any]:
    array = np.asarray(samples, dtype=np.float64)
    return {
        "median_ms": float(np.median(array)),
        "min_ms": float(array.min()),
        "p25_ms": float(np.percentile(array, 25)),
        "p75_ms": float(np.percentile(array, 75)),
        "samples_ms": [round(float(x), 4) for x in array],
    }


def verdict_for(ratio: float | None, tie_band_pct: float) -> str | None:
    if ratio is None:
        return None
    band = tie_band_pct / 100.0
    if abs(ratio - 1.0) <= band:
        return "within-band"
    return "prismq-sooner" if ratio > 1.0 else "comparator-sooner"


def total_variation_distance(left: np.ndarray, right: np.ndarray) -> float | None:
    if left.shape != right.shape:
        return None
    return float(0.5 * np.abs(left - right).sum())


def measure(
    program: corpus.Program, sims: list[Any], args: argparse.Namespace
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    timings: dict[str, Any] = {}
    equivalence: dict[str, Any] = {}
    errors: list[dict[str, str]] = []

    def record_error(sim: Any, exc: Exception) -> None:
        message = f"{type(exc).__name__}: {exc}"[:200]
        errors.append({"simulator": sim.name, "error": message})

    reference_sim = next((s for s in sims if s.name == REFERENCE_SIMULATOR), sims[0])
    reference: np.ndarray | None = None
    try:
        reference = reference_sim.probabilities(program)
    except Exception as exc:  # noqa: BLE001
        record_error(reference_sim, exc)

    # One vector at a time: at 26 qubits each is 512 MB.
    for sim in sims:
        if sim is reference_sim:
            if reference is not None:
                equivalence[sim.name] = {"tvd": 0.0, "pass": True}
            continue
        try:
            vector = sim.probabilities(program)
        except Exception as exc:  # noqa: BLE001
            record_error(sim, exc)
            continue
        if reference is None:
            equivalence[sim.name] = {"tvd": None, "pass": None, "reason": "no reference vector"}
        else:
            tvd = total_variation_distance(vector, reference)
            equivalence[sim.name] = {"tvd": tvd, "pass": tvd is not None and tvd <= args.equivalence_tvd}
        del vector
    del reference

    failed = {e["simulator"] for e in errors}
    for sim in sims:
        if sim.name in failed:
            timings[sim.name] = {"error": next(e["error"] for e in errors if e["simulator"] == sim.name)}
            continue
        try:
            timings[sim.name] = stats(sim.time(program, args.iterations))
        except Exception as exc:  # noqa: BLE001
            record_error(sim, exc)
            timings[sim.name] = {"error": errors[-1]["error"]}

    base = timings.get("prismq", {}).get("median_ms")
    ratios: dict[str, float | None] = {}
    verdicts: dict[str, str | None] = {}
    for sim in sims:
        if sim.name == "prismq":
            continue
        other = timings.get(sim.name, {}).get("median_ms")
        passed = equivalence.get(sim.name, {}).get("pass") is not False
        ratio = other / base if base and other and passed else None
        ratios[sim.name] = ratio
        verdicts[sim.name] = verdict_for(ratio, args.tie_band_pct)

    row = program.summary()
    row.update({"timings": timings, "equivalence": equivalence, "ratio_vs_prismq": ratios, "verdict": verdicts})
    return row, errors


def summarize(rows: list[dict[str, Any]], sims: list[Any], args: argparse.Namespace) -> dict[str, Any]:
    per_comparator: dict[str, Any] = {}
    headline = [r for r in rows if r["num_qubits"] >= args.headline_min_qubits]
    for sim in sims:
        if sim.name == "prismq":
            continue
        verdicts = [r["verdict"].get(sim.name) for r in headline]
        ratios = [r["ratio_vs_prismq"].get(sim.name) for r in headline]
        ratios = [x for x in ratios if x is not None]
        per_comparator[sim.name] = {
            "faster": verdicts.count("prismq-sooner"),
            "within_band": verdicts.count("within-band"),
            "slower": verdicts.count("comparator-sooner"),
            "median_ratio": float(np.median(ratios)) if ratios else None,
            "min_ratio": float(min(ratios)) if ratios else None,
            "max_ratio": float(max(ratios)) if ratios else None,
        }

    failures = []
    for row in rows:
        for name, entry in row["equivalence"].items():
            if entry.get("pass") is False:
                failures.append(
                    {
                        "benchmark": row["benchmark"],
                        "num_qubits": row["num_qubits"],
                        "simulator": name,
                        "tvd": entry["tvd"],
                    }
                )
    return {"per_comparator": per_comparator, "equivalence_failures": failures, "errors": []}


def settings_for(sim: Any) -> str:
    if sim.name == "prismq":
        return "BackendKind::Auto, fusion on, double precision, RAYON_NUM_THREADS pinned"
    if sim.name.startswith("aer-"):
        return f"method={sim.method}, fusion on (default), double precision, max_parallel_threads pinned"
    if sim.name == "qsim":
        return (
            "QSimOptions defaults (max_fused_gate_size 2), cpu_threads pinned; "
            "single precision, the only precision qsim offers"
        )
    if sim.name == "quest":
        return "static library, double precision, OpenMP on, OMP_NUM_THREADS pinned"
    if sim.name == "spinoza":
        return "default double feature, Config.threads pinned"
    if sim.name == "qip":
        return "LocalBuilder<f64>, parallel feature, RAYON_NUM_THREADS pinned"
    return ""


def run(args: argparse.Namespace) -> dict[str, Any]:
    if not args.no_build:
        build_runner()

    names = corpus.available_benchmarks() if args.families == "all" else [n.strip() for n in args.families.split(",") if n.strip()]
    sizes = [int(x) for x in args.qubits.split(",") if x.strip()]
    requested = [n.strip() for n in args.simulators.split(",") if n.strip()]
    if "prismq" not in requested:
        requested.insert(0, "prismq")

    warnings = provenance.quiet_machine_warnings()
    for message in warnings:
        print(f"warning: {message}", file=sys.stderr)

    sims = adapters.build_all(requested, args.threads, args.timeout_s)
    programs: list[corpus.Program] = []
    skipped: list[corpus.Skip] = []
    for size in sizes:
        for name in names:
            built = corpus.build(adapters.RUNNER, name, size)
            if isinstance(built, corpus.Skip):
                skipped.append(built)
            else:
                programs.append(built)

    print(
        f"{len(programs)} circuits to run, {len(skipped)} skipped, {args.iterations} iterations, "
        f"{args.threads} threads, simulators: {', '.join(s.name for s in sims)}",
        flush=True,
    )

    rows: list[dict[str, Any]] = []
    all_errors: list[dict[str, Any]] = []
    for index, program in enumerate(programs, start=1):
        print(
            f"  [{index}/{len(programs)}] {program.benchmark} {program.num_qubits}q ({program.num_operations} gates)",
            flush=True,
        )
        row, errors = measure(program, sims, args)
        rows.append(row)
        for error in errors:
            all_errors.append({"benchmark": program.benchmark, "num_qubits": program.num_qubits, **error})
            print(f"      {error['simulator']}: {error['error']}", flush=True)

    summary = summarize(rows, sims, args)
    summary["errors"] = all_errors

    overhead = {}
    for sim in sims:
        if isinstance(sim, adapters.Python):
            overhead[sim.name] = sim.fixed_overhead_ms()

    corpus_block = corpus.descriptor()
    corpus_block["skipped"] = [s.summary() for s in skipped]
    versions = {s.name: s.version() for s in sims}

    return {
        "schema_version": SCHEMA_VERSION,
        "run": {
            "iterations": args.iterations,
            "threads": args.threads,
            "sizes": sizes,
            "tie_band_pct": args.tie_band_pct,
            "equivalence_tolerance_tvd": args.equivalence_tvd,
            "reference_simulator": REFERENCE_SIMULATOR,
            "headline_min_qubits": args.headline_min_qubits,
            "timed_region": (
                "execute the circuit and materialize the full 2^n probability vector; "
                "building the circuit from the gate list is excluded on every side"
            ),
            "machine_warnings": warnings,
        },
        "provenance": provenance.collect(CARGO_FEATURES, args.threads, versions),
        "corpus": corpus_block,
        "adapters": {s.name: {"label": s.label, "version": versions[s.name], "settings": settings_for(s)} for s in sims},
        "fixed_overhead_ms": overhead,
        "results": rows,
        "summary": summary,
    }


def check(results: dict[str, Any], reference_path: str) -> int:
    with open(reference_path, encoding="utf-8") as handle:
        reference = json.load(handle)

    ref_rows = {(r["benchmark"], r["num_qubits"]): r for r in reference["results"]}
    problems: list[str] = []

    for row in results["results"]:
        key = (row["benchmark"], row["num_qubits"])
        ref = ref_rows.get(key)
        if ref is None:
            continue
        if ref["sha256"] != row["sha256"]:
            problems.append(
                f"{key[0]} {key[1]}q: circuit hash differs from reference "
                f"({ref['sha256'][:12]} vs {row['sha256'][:12]}); corpus is not the same"
            )
            continue
        for name, entry in row["equivalence"].items():
            if entry.get("pass") is False:
                problems.append(f"{key[0]} {key[1]}q: {name} output diverged, TVD {entry['tvd']:.2e}")
        for name, got in row["verdict"].items():
            expected = ref["verdict"].get(name)
            if expected is not None and got is not None and expected != got:
                problems.append(
                    f"{key[0]} {key[1]}q vs {name}: reference says {expected}, this run says "
                    f"{got} (ratio {ref['ratio_vs_prismq'].get(name):.2f}x -> "
                    f"{row['ratio_vs_prismq'].get(name):.2f}x)"
                )

    print()
    if problems:
        print(f"CHECK FAILED: {len(problems)} discrepancies against {reference_path}")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print(f"CHECK PASSED against {reference_path}")
    print("  circuit hashes match, outputs agree, and every verdict held")
    return 0


def main() -> int:
    args = parse_args()
    results = run(args)

    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w", encoding="utf-8") as handle:
            json.dump(results, handle, indent=2)
        print(f"\nwrote {args.out}")

    markdown = report.render(results)
    if args.markdown:
        with open(args.markdown, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(markdown)
        print(f"wrote {args.markdown}")
    else:
        print()
        print(markdown)

    if args.docs:
        body = markdown.split("\n", 1)[1].lstrip("\n")
        with open(args.docs, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(DOCS_PREAMBLE + body + DOCS_FOOTER)
        print(f"wrote {args.docs}")

    if args.check:
        return check(results, args.check)

    if results["summary"]["equivalence_failures"]:
        print("\nFAILED: at least one simulator produced a different distribution")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
